export const NEW_YORK_TRACER_PACKAGE = Object.freeze({
  schemaVersion: 1,
  id: 'new-york-disordered-archive-tracer',
  version: '0.1.0-dev',
  status: 'development',
  title: '失序的城市档案 · 开发纵切',
  city: 'New York',
  releaseCriteria: {
    anchorCount: 36,
    segmentCounts: { 'shared-opening': 3, case: 30, 'final-reasoning': 3 },
    caseAnchorCounts: {
      'manhattan-time-tracer': 10,
      'brooklyn-shoreline': 10,
      'queens-future': 10,
    },
  },
  cases: [{
    id: 'manhattan-time-tracer',
    title: '曼哈顿时间档案案 · 纵切',
    truth: '公共时间系统必须保留各自的先后与用途。',
    endingId: 'archive-sequence-restored',
  }],
  sources: [{
    id: 'nyc-parks-bowling-green',
    institution: 'NYC Parks',
    title: 'Bowling Green history',
    url: 'https://nycgovparks.org/about/history/bowling-boules-bocce',
    verified: '2026-09-07',
  }],
  evidence: [
    { id: 'boundary-evidence', label: '地点边界证据', sourceRefs: ['nyc-parks-bowling-green'] },
    { id: 'case-sequence-evidence', label: '公共时序证据', sourceRefs: ['nyc-parks-bowling-green'] },
  ],
  graph: {
    startNodeId: 'opening-bowling-green',
    nodes: [
      {
        id: 'opening-bowling-green',
        segment: 'shared-opening',
        title: '共享开场 · 地点边界',
        fact: 'Bowling Green 的公共空间历史为识别城市档案边界提供起点。',
        fantasy: '失序档案异常正在抹去地点之间的边界关系。',
        sourceRefs: ['nyc-parks-bowling-green'],
        streetViewTarget: {
          position: { lat: 40.70408, lng: -74.01317 },
          radiusMetres: 35,
          heading: 18,
          headingTolerance: 20,
          routeStatus: 'needs-live-check',
        },
        interaction: {
          prompt: '确认公园边界与街道的关系。',
          actions: [{ id: 'observe-boundary', label: '提交边界观察' }],
          grantsEvidence: ['boundary-evidence'],
        },
        fallback: { id: 'opening-public-fallback', mode: 'continue-with-authored-context' },
      },
      {
        id: 'case-public-time',
        segment: 'case',
        caseId: 'manhattan-time-tracer',
        title: '案件锚点 · 公共时序',
        fact: 'NYC Parks 的资料记录了 Bowling Green 公共空间跨时期的用途。',
        fantasy: '异常正把不同公共用途伪造成一条没有因果的时间线。',
        sourceRefs: ['nyc-parks-bowling-green'],
        streetViewTarget: {
          position: { lat: 40.70368, lng: -74.01091 },
          radiusMetres: 45,
          heading: 292,
          headingTolerance: 25,
          routeStatus: 'needs-live-check',
        },
        interaction: {
          prompt: '把地点用途加入案件时序。',
          actions: [{ id: 'record-sequence', label: '提交时序证据' }],
          requiresEvidence: ['boundary-evidence'],
          grantsEvidence: ['case-sequence-evidence'],
        },
        fallback: { id: 'case-public-fallback', mode: 'continue-with-authored-context' },
      },
      {
        id: 'final-reasoning',
        segment: 'final-reasoning',
        title: '最终推理 · 恢复先后',
        fact: 'Bowling Green 的机构记录保留了公共空间用途的历史层次。',
        fantasy: '小组用证据恢复了被失序档案混合的先后关系。',
        sourceRefs: ['nyc-parks-bowling-green'],
        streetViewTarget: {
          position: { lat: 40.70542, lng: -74.01347 },
          radiusMetres: 50,
          heading: 205,
          headingTolerance: 30,
          routeStatus: 'needs-live-check',
        },
        interaction: {
          prompt: '用已收集证据恢复公共时间的因果顺序。',
          actions: [{ id: 'restore-sequence', label: '恢复档案顺序' }],
          requiresEvidence: ['boundary-evidence', 'case-sequence-evidence'],
        },
        fallback: { id: 'final-public-fallback', mode: 'continue-with-authored-context' },
      },
    ],
    edges: [
      { from: 'opening-bowling-green', to: 'case-public-time' },
      { from: 'case-public-time', to: 'final-reasoning' },
    ],
  },
  geography: {
    routes: [
      {
        from: 'opening-bowling-green', to: 'case-public-time',
        transition: 'coordinate', routeStatus: 'needs-live-check',
      },
      {
        from: 'case-public-time', to: 'final-reasoning',
        transition: 'coordinate', routeStatus: 'needs-live-check',
      },
    ],
  },
  endings: [{
    id: 'archive-sequence-restored',
    caseId: 'manhattan-time-tracer',
    title: '公共时序已恢复',
    requiresEvidence: ['boundary-evidence', 'case-sequence-evidence'],
    cultureCard: { id: 'manhattan-time-card' },
  }],
});
